### ISSUE TITLE
License, port?

### ISSUE THREAD

**Issue by stochaztic** [abyssonym/bizarre_dimension#2]
Hey, I've been considering beginning work on porting this rando to Javascript so it can be hosted on a website with no download necessary, and was wondering 1) if you would be alright with this idea, and 2) if you would be willing to set an open-source license of some variety on this repo and the randomtools repo, or otherwise explicitly grant permissions for such a project.

Obviously this would be a large undertaking so I wanted to clear these issues up before I started planning for it. Thanks!

**Comment by abyssonym** [comment]
Sure that's fine. I believe someone has already done something similar for the SMRPG randomizer I made. I've selected the GNU GPLv3 license for the specified projects.

**Comment by stochaztic** [comment]
Thanks!
